### PR TITLE
Ongoing changelog for 4.5.8-0 part1 #6

### PR DESCRIPTION
**Pull request by phillxnet**
Modify changelog re progress using release version to denote the next GitHub PR to be test built with the indicated changes.

### CODE REVIEW

**Comment by phillxnet** [comment]
@FroggyFlox @Hooverdan96

Still fathoming how best to do this, but for now we can do in parts against the indicated issue. I'm hoping to resolve another issue on the current Milestone and I believe @FroggyFlox may have a pr in the making also. If so we can associated a part2 pr to that end. And then finish off with a full on Version and jslib version change for the final builds.

**Comment by phillxnet** [comment]
A 4.5.7-0 installed rpm displayed the following when the resulting 4.5.7-2511 rpm was build to test the indicated pr in core, and the most recent issue in the adjusted changelog.
2511-rpm-changelog-result

**Comment by Hooverdan96** [comment]
Thanks for the info. I completely forgot about the need for yum w.r.t the changelog.

**Comment by phillxnet** [comment]
@Hooverdan96 Your welcome. Yes the yum thing is a real extra weigh as it goes, or rather dnf-yum as we have now.
I'm looking forward to when we can drop it entirely as it's silly having both in parallel. Although the yum is a very sparse setup with only our one repo at a time: testing or stable.

**Comment by Hooverdan96** [comment]
I assume, you've been at some point tracking this request here: https://github.com/openSUSE/zypper/issues/138

Not sure about the last statement in that thread that the changelog option is now available in Tumbleweed, but in Leap it's actually still using yum (and is that "standard" in Leap)?

**Comment by phillxnet** [comment]
> I assume, you've been at some point tracking this request here: [openSUSE/zypper#138](https://github.com/openSUSE/zypper/issues/138)

Yes, we actually have a reference to it in our existing code:

https://github.com/rockstor/rockstor-core/blob/6db3cb1fa43514d6c1e2581d939d6840552f2c05/src/rockstor/system/pkg_mgmt.py#L502-L505

It's been a long time missing and someone did write a zypper addition for this but upstream had, in the interim, changed a tone of stuff. So the work was not able to be incorporated!

**Comment by phillxnet** [comment]
> Well, in any case, this is probably a less important detail to worry about at this time.

Agreed. Plus I think the referenced zypper plugin doesn't look to that actively maintained. We will have to have a focused issue on our options when we are past this Milestone I think as it will massively simplify our package stuff. Especially once we also throw our all our CentOS stuff, for older versions of yum etc. But don't want to mess with stuff too much as we edge towards the next stable.

**Pull request merged**
